[package]
name = "cfg_parser"
version = "0.1.0"
edition = "2024"
authors = ["Juan Manuel Young Hoyos"]

[[bin]]
name = "cfg_parser"
path = "src/main.rs"

[dependencies]
thiserror = "2.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
